agenda/urls.py
from django.urls import path
from . import views

app_name = 'agenda'

urlpatterns = [
    path('', views.home, name='home'),
    path('busca/', views.search, name='search'),
    path('agenda/contato/<int:id_contact>/', views.contact, name='contact'),
    path('delete/<int:id_contact_delete>/', views.delete, name='delete'),
    path('update/<int:id_contact_update>/', views.update, name='update'),
    path('add/', views.add_contact, name='add'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('agenda.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agenda/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30, blank=True, null=True)
    telephone = models.CharField(max_length=20)
    email = models.CharField(max_length=255, blank=True, null=True)
    created_in = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True
    )
    profile_picture = models.ImageField(
        blank=True,
        upload_to='agenda/img/%Y/%m/%d'
    )
    to_show = models.BooleanField(default=True)

    def __str__(self):
        return self.first_name

agenda/forms.py
from .models import Contact
from django import forms


class NewContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ('to_show',)

        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'class': 'form-control',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'telephone': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 5,
                    'placeholder': 'escreva uma breve descrição para o contato'
                }
            ),
            'category': forms.Select(
                attrs={
                    'class': 'form-select form-select-sm',
                    'arial-label': '.form-select-sm example'
                }
            ),
            'profile_picture': forms.FileInput(
                attrs={
                    'class': 'form-control form-control-sm'
                }
            )
        }

agenda/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q, Value as V
from django.core.paginator import Paginator
from django.db.models.functions import Concat
from django.contrib import messages
from .models import Contact
from .forms import NewContactForm


def home(request):
    contacts = Contact.objects.all().filter(
        to_show=True
    ).order_by('first_name')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    form = NewContactForm()

    return render(request, 'agenda/pages/home.html', context={
            'contacts': page_obj,
            'form': form
        }
    )


def add_contact(request):
    if request.method == 'POST':
        form = NewContactForm(request.POST, request.FILES)

        if form.is_valid():
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')

            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                'Contato %s %s adicionado com sucesso.' % (
                        first_name,
                        last_name
                    )
            )
            return redirect('agenda:home')


def search(request):
    term = request.GET.get('term')

    if term is None or not term:
        messages.add_message(
            request,
            messages.ERROR,
            'Opss! campo de busca vazio.'
            )
        return redirect('agenda:home')

    field_search_contact = Concat('first_name', V(' '), 'last_name')
    contacts = Contact.objects.annotate(
        full_name=field_search_contact
    ).filter(
        Q(full_name__icontains=term) |
        Q(telephone__icontains=term),
        to_show=True
    )
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if len(contacts.values()) == 0:
        messages.add_message(
            request,
            messages.WARNING,
            '%i contato(s) encontrados' % (len(contacts.values()))
            )
    else:
        messages.add_message(
            request,
            messages.SUCCESS,
            '%i contato(s) encontrados' % (len(contacts.values()))
            )
    return render(request, 'agenda/pages/search_contact.html', context={
        'contacts': page_obj
    })


def contact(request, id_contact):
    contact = get_object_or_404(Contact, id=id_contact)
    form = NewContactForm(instance=contact)
    return render(request, 'agenda/pages/contact.html', context={
            'contact': contact,
            'form': form
        }
    )


def delete(request, id_contact_delete):
    contact_delete = get_object_or_404(Contact, id=id_contact_delete)
    contact_delete.delete()
    messages.add_message(
        request,
        messages.SUCCESS,
        'Contato %s %s apagado com sucesso.' % (
            contact_delete.first_name,
            contact_delete.last_name
        )
    )
    return redirect('agenda:home')


def update(request, id_contact_update):
    if request.method == 'POST':
        contact = get_object_or_404(Contact, id=id_contact_update)
        form = NewContactForm(
                request.POST,
                request.FILES or None,
                instance=contact
            )

        if form.is_valid():
            form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                'Contato atualizado com sucesso.'
            )
            return redirect('agenda:contact', contact.id)

agenda/templates/agenda/pages/contact.html
{% extends 'global/base.html' %}

{% block title %}Agenda | {{ contact.first_name }} {{contact.last_name }}{% endblock title %}

{% block content %}
<!-- Page Content -->
<div class="container">
    <div class="row">

        {% include 'agenda/partials/_alerts.html' %}

        <div class="col-lg-12">
            <div class="contact-name">
                <h1 class="mt-5">{{ contact.first_name | title }} {{ contact.last_name | title }}</h1>       
            </div>
            {% if contact.profile_picture %}
                <img src="{{ contact.profile_picture.url }}" class="img-thumbnail image-profile rounded shadow mb-3" alt="image contact profile">
            {% endif %}

            <dl>
                <dt>ID</dt>
                <dd>{{ contact.id }}</dd>

                <dt>Telefone</dt>
                <dd>{{ contact.telephone }}</dd>

                <dt>E-mail</dt>
                <dd>{{ contact.email }}</dd>

                <dt>Data criação</dt>
                <dd>{{ contact.created_in }}</dd>

                <dt>Categoria</dt>
                <dd>{{ contact.category }}</dd>

                <dt>Descrição</dt>
                <dd>{{ contact.description | capfirst }}</dd>

                <dt>
                    <hr class="border-3 opacity-75">
                </dt>
                <dd>
                    <a class="btn btn-dark bg-gradient shadow" href="{% url 'agenda:home' %}" >  
                        <i class="text-white fa-solid fa-arrow-left"></i>
                        <span class="text-white">back</span> 
                    </a>
                    <button type="button" class="ms-3 btn btn-primary bg-gradient shadow" data-bs-toggle="modal" href="#exampleModalToggle" role="button"> 
                        <i class="text-dank fa-solid fa-user-pen"></i>
                        <span class="text-white">to edit</span>
                    </button>
                    <button type="button" class="btn btn-danger ms-3 bg-gradient shadow" data-bs-toggle="modal" data-bs-target="#exampleModal">    
                        <i class="text-white fa-solid fa-trash-can"></i>
                        <span class="text-white">delete</span>
                    </button>
                </dd>
            </dl>
            {% include 'agenda/partials/_modal_to_edit.html' %}
            {% include 'agenda/partials/_modal_delete.html' %}
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
<footer>
    <span>powered by Django</span>
</footer>
{% endblock footer %}

agenda/templates/agenda/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Agenda{% endblock title %}

{% block content %}

{% include 'agenda/partials/_nav.html' %}

<!-- Page Content -->
<div class="container-md">
    <div class="row">
        <div class="col-lg-12">

        {% include 'agenda/partials/_btn_action.html' %}
        {% include 'agenda/partials/_alerts.html' %}

        <table class="table table-hover">
            <thead>
                <tr class="table-dark shadow">
                    <th>Nome</th>
                    <th>Sobrenome</th>
                    <th>Email</th>
                    <th>Telefone</th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
            {% for contact in contacts %}
                {% include 'agenda/partials/_modal_add.html' %}
                {% if contact.to_show %}
                    <tr>
                        <td>
                            <a href="{% url 'agenda:contact' contact.id %}">{{ contact.first_name | title }}</a>
                        </td>
                        <td>
                            <a href="{% url 'agenda:contact' contact.id %}">{{ contact.last_name | title }}</a>
                        </td>
                        <td>{{ contact.email }}</td>
                        <td>{{ contact.telephone }}</td>
                        <td>{{ contact.category }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

        </div>
        {% include 'agenda/partials/_pagination.html' %}
    </div>
</div>
{% endblock content %}

{% block footer %}
<footer>
    <span>powered by Django</span>
</footer>
{% endblock footer %}

agenda/templates/agenda/pages/search_contact.html
{% extends 'global/base.html' %}

{% block title %}Agenda{% endblock title %}

{% block content %}

{% include 'agenda/partials/_nav.html' %}

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            {% include 'agenda/partials/_btn_action.html' %}
            {% include 'agenda/partials/_alerts.html' %}
       
            <table class="table table-hover">
                <thead>
                    <tr class="table-dark shadow">
                        <th>Nome</th>
                        <th>Sobrenome</th>
                        <th>Email</th>
                        <th>Telefone</th>
                        <th>Categoria</th>
                    </tr>
                </thead>
                <tbody>
                {% for contact in contacts %}
                    {% if contact.to_show %}
                        <tr>
                            <td>
                                <a href="{% url 'agenda:contact' contact.id %}">{{ contact.first_name | title }}</a>
                            </td>
                            <td>
                                <a href="{% url 'agenda:contact' contact.id %}">{{ contact.last_name | title }}</a>
                            </td>
                            <td>{{ contact.email }}</td>
                            <td>{{ contact.telephone }}</td>
                            <td>{{ contact.category }}</td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
        {% include 'agenda/partials/_pagination.html' %}
    </div>
</div>
{% endblock content %}

{% block footer %}
<footer>
    <span>powered by Django</span>
</footer>
{% endblock footer %}

agenda/templates/agenda/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} messages-alert alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}   
{% endif %}

agenda/templates/agenda/partials/_btn_action.html
<h1 class="mt-4">Olá, {{ user.first_name }} {{ user.last_name }}.</h1>
<div class="action-btn">
    <h4 class="mb-3 text-primary lead">aqui estão listado seus contatos.</h4>
    <div class="action">
        <button type="button" class="btn btn-primary bg-gradiente btn-sm shadow" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
            <i class="text-white fa-solid fa-plus"></i>
            <span class="text-white">adicionar contato</span>
        </button>
        <a class="btn btn-dark bg-gradiente btn-sm ms-3 shadow" href="{% url 'agenda:home' %}">
            <i class="text-white fa-solid fa-list"></i>
            <span class="text-white">todos contatos</span>
        </a>
    </div>
</div>

agenda/templates/agenda/partials/_modal_add.html
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="staticBackdropLabel">Adicionar Contato</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'agenda:add' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">
                    <p class="text-muted lead">
                        obs: os campos marcados com <span class="text-danger">*</span> são obrigatórios.
                    </p>
                    <div class="row">
                        <div class="col">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label text-primary">
                                Nome<span class="text-danger">*</span>
                            </label>
                            {{ form.first_name }}
                            <small class="text-danger">{{ form.first_name.errors.as_text }}</small>
                        </div>
                        <div class="col">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label text-primary">
                                Sobrenome
                            </label>
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.telephone.id_for_label }}" class="form-label text-primary">
                            Telefone<span class="text-danger">*</span>
                        </label>
                        {{ form.telephone }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.email.id_for_label }}" class="form-label text-primary">
                            Endereço de Email
                        </label>
                        {{ form.email }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.category.id_for_label }}" class="form-label text-primary">
                            Categoria
                        </label>
                        {{ form.category }}
                        <small class="text-danger">{{ forms.category.errors.as_text }}</small>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.description.id_for_label }}" class="form-label text-primary">
                            Descrição
                        </label>
                        {{ form.description }}
                        <small class="text-danger">{{ forms.description.errors.as_text }}</small>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.profile_picture.id_for_label }}" class="form-label text-primary">
                           Imagem de perfil
                        </label>
                        {{ form.profile_picture }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger bg-gradiente shadow" data-bs-dismiss="modal">Abandonar</button>
                    <button type="submit" class="btn btn-success bg-gradiente shadow">Criar Contato</button>
                </div>
            </form>
        </div>
    </div>
</div>

agenda/templates/agenda/partials/_modal_delete.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="exampleModalLabel">Excluir contato</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p class="lead">
                    deseja deletar o contato <span class="text-primary">{{ contact.first_name }} {{ contact.last_name }}</span> ?
                </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger bg-gradient shadow" data-bs-dismiss="modal">Não</button>
                <a href="{% url 'agenda:delete' contact.id %}">
                    <button type="button" class="btn btn-success bg-gradient shadow">Sim</button>
                </a>
            </div>
        </div>
    </div>
</div>

agenda/templates/agenda/partials/_modal_to_edit.html
<div class="modal fade" id="exampleModalToggle" aria-hidden="true" aria-labelledby="exampleModalToggleLabel" tabindex="-1">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="exampleModalToggleLabel">Editar Contato</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form action="{% url 'agenda:update' contact.id %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="modal-body">
                    <p class="text-muted lead">
                        obs: os campos marcados com <span class="text-danger">*</span> são obrigatórios.
                    </p>
                    <div class="row">
                        <div class="col">
                            <label for="{{ form.first_name.id_for_label }}" class="form-label text-primary">
                                Nome<span class="text-danger">*</span>
                            </label>
                            {{ form.first_name }}
                            <small class="text-danger">{{ form.first_name.errors.as_text }}</small>
                        </div>
                        <div class="col">
                            <label for="{{ form.last_name.id_for_label }}" class="form-label text-primary">
                                Sobrenome
                            </label>
                            {{ form.last_name }}
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.telephone.id_for_label }}" class="form-label text-primary">
                            Telefone<span class="text-danger">*</span>
                        </label>
                        {{ form.telephone }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.email.id_for_label }}" class="form-label text-primary">
                            Endereço de Email
                        </label>
                        {{ form.email }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.category.id_for_label }}" class="form-label text-primary">
                            Categoria
                        </label>
                        {{ form.category }}
                        <small class="text-danger">{{ forms.category.errors.as_text }}</small>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.description.id_for_label }}" class="form-label text-primary">
                            Descrição
                        </label>
                        {{ form.description }}
                        <small class="text-danger">{{ forms.description.errors.as_text }}</small>
                    </div>
                    <div class="mb-3">
                        <label for="{{ form.profile_picture.id_for_label }}" class="form-label text-primary">
                           Imagem de perfil
                        </label>
                        {{ form.profile_picture }}
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger bg-gradiente shadow" data-bs-dismiss="modal">Abandonar</button>
                    <button type="submit" class="btn btn-success bg-gradiente shadow" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>

agenda/templates/agenda/partials/_nav.html
{% load static %}
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow">
    <div class="container-sm">
        <a class="navbar-brand" href="{% url 'agenda:home' %}">
            <img src="{% static 'agenda/img/telefone.svg' %}" alt="">
            Agenda
        </a>

        <form  action="{% url 'agenda:search' %}" method="GET" class="d-flex" role="search">
            <input class="form-control me-2" type="search" value="{{ request.GET.term }}"name="term" placeholder="buscar contato" aria-label="Search">
            <button class="btn btn-primary bg-gradient d-flex justify-content-evenly align-items-center" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                </svg>
                <span class="text-white ms-1">search</span>
            </button>
        </form>
    </div>
</nav>

agenda/templates/agenda/partials/_pagination.html
<div aria-label="Page navigation example">
    <ul class="pagination">
        {% for page in contacts.paginator.page_range %}
            {% if contacts.number == page %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ page }}&term={{ request.GET.term }}">{{ page }}</a>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page }}&term={{ request.GET.term }}">{{ page }}</a>
                </li>
            {% endif %}
        {% endfor %}
    
    </ul>
</div>